"""collab_is_on

Revision ID: 38c164eed572
Revises: 6a4977393fbf
Create Date: 2024-02-20 14:40:03.025614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c164eed572'
down_revision = '6a4977393fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notes_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborators')
    # ### end Alembic commands ###
