"""Added new fields to notes model

Revision ID: 932072c7d0ff
Revises: 61291af6593d
Create Date: 2024-02-15 11:50:49.882841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932072c7d0ff'
down_revision = '61291af6593d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_trash', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('is_trash')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
